### ISSUE TITLE
Mention not working when added in task description

### ISSUE THREAD

**Issue by Grizzlik** [tainewoo/redmine_mentions#4]
It seems that emails are sent only when people are mentioned in task's comments. When I add mention to task's main description (for new or for existing tasks), no email arrives.

**Comment by tainewoo** [comment]
Hi @Grizzlik ,

Thank you for your issue.
Yes, currently this plugin only trigger the notification when users are mentioned in the notes/comments.

**Comment by Grizzlik** [comment]
Thanks. I though also task descriptions ought to be triggered, but I checked the description of plugin again and really, there are only notes/comments mentioned.
So I'm closing this issue (as it is more of a feature request :)).

**Comment by tainewoo** [comment]
Hi @Grizzlik ,

Currently this plugin only works with notes.
And yes i also considered about applying it to the description, i need to diff the description and avoid sending unnecessary notifications if the user is not just added to the description. 
Maybe i will implement it later, PR is also welcome too.
